// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifgyqsldumyylifcwayj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmZ3lxc2xkdW15eWxpZmN3YXlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0Mjk3MjIsImV4cCI6MjA2NjAwNTcyMn0.2z5VIM-TMmIs3zm2QGUQRjf2Jda7k09BwpVREjLyKw0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);